import type {
  Event,
  EventParkingSpace,
  Reservation,
  User,
} from '@/types';

// 초기 시드 데이터. `npm run db:seed`가 SQLite에 적재하며, 역할별 화면 가드가 SEED_IDS를 참조함
export const SEED_IDS = {
  GUEST: 'user-guest-1',
  GUEST2: 'user-guest-2',
  GUEST3: 'user-guest-3',
  HOST: 'user-host-1',
  ADMIN: 'user-admin-1',
  EVENT_JAMSIL: 'event-jamsil',
  EVENT_SANGAM: 'event-sangam',
  EVENT_GOCHEOK: 'event-gocheok',
  SPACE_ISSUE: 'space-1',
  SPACE_APPROVED: 'space-2',
  SPACE_PENDING: 'space-3',
  SPACE_RESERVED: 'space-4',
  SPACE_JAMSIL_A: 'space-5',
  SPACE_JAMSIL_B: 'space-6',
  SPACE_REJECTED: 'space-7',
  SPACE_CLOSED_A: 'space-8',
  SPACE_CLOSED_B: 'space-9',
  SPACE_PENDING_2: 'space-10',
  SPACE_JAMSIL_C: 'space-11',
  SPACE_JAMSIL_D: 'space-12',
  SPACE_JAMSIL_E: 'space-13',
} as const;

interface DB {
  users: User[];
  events: Event[];
  spaces: EventParkingSpace[];
  reservations: Reservation[];
}

export function seedDB(): DB {
  const users: Omit<User, 'created_at'>[] = [
      {
        user_id: SEED_IDS.GUEST,
        name: '김게스트',
        phone_number: '01011111111',
        vehicle_plate_number: '12가3456',
        vehicle_model: '아반떼',
        role_type: 'USER',
      },
      {
        user_id: SEED_IDS.GUEST2,
        name: '이하나',
        phone_number: '01033333333',
        vehicle_plate_number: '34나5678',
        vehicle_model: '카니발',
        role_type: 'USER',
      },
      {
        user_id: SEED_IDS.GUEST3,
        name: '정하늘',
        phone_number: '01044444444',
        vehicle_plate_number: '56다7890',
        vehicle_model: '쏘렌토',
        role_type: 'USER',
      },
      {
        user_id: SEED_IDS.HOST,
        name: '박호스트',
        phone_number: '01022222222',
        role_type: 'USER',
      },
      {
        user_id: SEED_IDS.ADMIN,
        name: '최운영',
        phone_number: '01099999999',
        role_type: 'ADMIN',
      },
    ];

  const events: Omit<Event, 'created_by' | 'created_at' | 'updated_at'>[] = [
      {
        event_id: SEED_IDS.EVENT_JAMSIL,
        name: '2026 서울세계불꽃축제',
        venue_name: '여의도한강공원',
        address: '서울 영등포구 여의동로 330',
        start_datetime: '2026-10-03T18:00:00',
        end_datetime: '2026-10-03T21:30:00',
        status: 'UPCOMING',
      },
      {
        event_id: SEED_IDS.EVENT_SANGAM,
        name: '2026 한강 가을 페스티벌 (뚝섬)',
        venue_name: '뚝섬한강공원',
        address: '서울 광진구 강변북로 139',
        start_datetime: '2026-09-16T17:00:00',
        end_datetime: '2026-09-16T21:30:00',
        status: 'ONGOING',
      },
      {
        event_id: SEED_IDS.EVENT_GOCHEOK,
        name: '반포 밤도깨비 야시장',
        venue_name: '반포한강공원',
        address: '서울 서초구 신반포로11길 40',
        start_datetime: '2026-08-01T18:00:00',
        end_datetime: '2026-08-01T22:30:00',
        status: 'CLOSED',
      },
    ];

  const spaces: Omit<EventParkingSpace, 'created_at'>[] = [
      {
        space_id: SEED_IDS.SPACE_ISSUE,
        event_id: SEED_IDS.EVENT_SANGAM,
        host_id: SEED_IDS.HOST,
        address: '서울 성동구 성수동1가 685 (상가 주차장)',
        photo_url: 'https://placehold.co/400x300?text=Parking+1',
        walking_minutes: 5,
        entry_notes: 'SUV 진입 불가',
        price: 20000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_APPROVED,
        event_id: SEED_IDS.EVENT_SANGAM,
        host_id: SEED_IDS.HOST,
        address: '서울 광진구 자양동 227',
        photo_url: 'https://placehold.co/400x300?text=Parking+2',
        walking_minutes: 8,
        price: 15000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_PENDING,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 44 (오피스텔 방문주차)',
        photo_url: 'https://placehold.co/400x300?text=Parking+3',
        walking_minutes: 10,
        price: 18000,
        status: 'PENDING',
      },
      {
        space_id: SEED_IDS.SPACE_RESERVED,
        event_id: SEED_IDS.EVENT_SANGAM,
        host_id: SEED_IDS.HOST,
        address: '서울 광진구 구의동 100',
        photo_url: 'https://placehold.co/400x300?text=Parking+4',
        walking_minutes: 3,
        price: 25000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_JAMSIL_A,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 15 (오피스텔 지하주차장)',
        photo_url: 'https://placehold.co/400x300?text=Parking+5',
        walking_minutes: 6,
        entry_notes: '저녁 6시 이후 방문객 주차 가능, 지하 2층 B구역',
        price: 22000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_JAMSIL_B,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 23 (상가 주차장)',
        photo_url: 'https://placehold.co/400x300?text=Parking+6',
        walking_minutes: 12,
        price: 14000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_REJECTED,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 60 (이면도로)',
        photo_url: 'https://placehold.co/400x300?text=Parking+7',
        walking_minutes: 4,
        entry_notes: '불법 주정차 단속 구역으로 확인되어 반려',
        price: 30000,
        status: 'REJECTED',
      },
      {
        space_id: SEED_IDS.SPACE_CLOSED_A,
        event_id: SEED_IDS.EVENT_GOCHEOK,
        host_id: SEED_IDS.HOST,
        address: '서울 서초구 반포동 45',
        photo_url: 'https://placehold.co/400x300?text=Parking+8',
        walking_minutes: 7,
        price: 20000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_CLOSED_B,
        event_id: SEED_IDS.EVENT_GOCHEOK,
        host_id: SEED_IDS.HOST,
        address: '서울 서초구 잠원동 60',
        photo_url: 'https://placehold.co/400x300?text=Parking+9',
        walking_minutes: 9,
        price: 16000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_PENDING_2,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 76 (빌라 전면)',
        photo_url: 'https://placehold.co/400x300?text=Parking+10',
        walking_minutes: 9,
        entry_notes: '경차만 진입 가능',
        price: 17000,
        status: 'PENDING',
      },
      {
        space_id: SEED_IDS.SPACE_JAMSIL_C,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 88 (교회 주차장)',
        photo_url: 'https://placehold.co/400x300?text=Parking+11',
        walking_minutes: 7,
        entry_notes: '평일 저녁·주말만 개방',
        price: 19000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_JAMSIL_D,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 12 (오피스 야외주차장)',
        photo_url: 'https://placehold.co/400x300?text=Parking+12',
        walking_minutes: 4,
        price: 26000,
        status: 'APPROVED',
      },
      {
        space_id: SEED_IDS.SPACE_JAMSIL_E,
        event_id: SEED_IDS.EVENT_JAMSIL,
        host_id: SEED_IDS.HOST,
        address: '서울 영등포구 여의도동 5 (단독주택 마당)',
        photo_url: 'https://placehold.co/400x300?text=Parking+13',
        walking_minutes: 15,
        entry_notes: '대형차 진입 불가',
        price: 12000,
        status: 'APPROVED',
      },
    ];

  const reservations: Omit<Reservation, 'created_at'>[] = [
      {
        reservation_id: 'res-1',
        space_id: SEED_IDS.SPACE_RESERVED,
        guest_id: SEED_IDS.GUEST,
        vehicle_plate_number: '12가3456',
        payment_amount: 25000,
        status: 'CONFIRMED',
        is_checked_in: true,
        is_checked_out: false,
        is_refunded: false,
        is_payout_done: false,
        issue_note: null,
      },
      {
        reservation_id: 'res-2',
        space_id: SEED_IDS.SPACE_ISSUE,
        guest_id: SEED_IDS.GUEST,
        vehicle_plate_number: '12가3456',
        payment_amount: 20000,
        status: 'ISSUE_REPORTED',
        is_checked_in: true,
        is_checked_out: false,
        is_refunded: false,
        is_payout_done: false,
        issue_note: '[GUEST / 2026-09-16 19:20] 다른 차량이 자리에 주차되어 있습니다.',
      },
      {
        reservation_id: 'res-3',
        space_id: SEED_IDS.SPACE_JAMSIL_A,
        guest_id: SEED_IDS.GUEST,
        vehicle_plate_number: '12가3456',
        payment_amount: 22000,
        status: 'CONFIRMED',
        is_checked_in: false,
        is_checked_out: false,
        is_refunded: false,
        is_payout_done: false,
        issue_note: null,
      },
      {
        reservation_id: 'res-4',
        space_id: SEED_IDS.SPACE_CLOSED_A,
        guest_id: SEED_IDS.GUEST,
        vehicle_plate_number: '12가3456',
        payment_amount: 20000,
        status: 'COMPLETED',
        is_checked_in: true,
        is_checked_out: true,
        is_refunded: false,
        is_payout_done: false,
        issue_note: null,
      },
      {
        reservation_id: 'res-5',
        space_id: SEED_IDS.SPACE_CLOSED_B,
        guest_id: SEED_IDS.GUEST2,
        vehicle_plate_number: '34나5678',
        payment_amount: 16000,
        status: 'COMPLETED',
        is_checked_in: true,
        is_checked_out: true,
        is_refunded: false,
        is_payout_done: true,
        issue_note: null,
      },
      {
        reservation_id: 'res-6',
        space_id: SEED_IDS.SPACE_APPROVED,
        guest_id: SEED_IDS.GUEST,
        vehicle_plate_number: '12가3456',
        payment_amount: 15000,
        status: 'CANCELLED',
        is_checked_in: false,
        is_checked_out: false,
        is_refunded: true,
        is_payout_done: false,
        issue_note:
          '[GUEST / 2026-09-15 18:40] 진입로가 사유차량으로 막혀 있어 주차 불가합니다.\n[ADMIN / 2026-09-15 19:05] 현장 확인 후 전액 환불 처리 완료.',
      },
      {
        reservation_id: 'res-7',
        space_id: SEED_IDS.SPACE_JAMSIL_B,
        guest_id: SEED_IDS.GUEST3,
        vehicle_plate_number: '56다7890',
        payment_amount: 14000,
        status: 'CONFIRMED',
        is_checked_in: false,
        is_checked_out: false,
        is_refunded: false,
        is_payout_done: false,
        issue_note: null,
      },
      {
        reservation_id: 'res-8',
        space_id: SEED_IDS.SPACE_APPROVED,
        guest_id: SEED_IDS.GUEST,
        vehicle_plate_number: '12가3456',
        payment_amount: 15000,
        status: 'ISSUE_REPORTED',
        is_checked_in: false,
        is_checked_out: false,
        is_refunded: false,
        is_payout_done: false,
        issue_note: '[GUEST / 2026-09-16 17:40] 예약한 자리 진입로에 이면주차 차량이 있어 도착 전인데 진입이 불가능해 보입니다.',
      },
    ];

  const now = new Date().toISOString();
  return {
    users: users.map((u) => ({ ...u, created_at: now })),
    events: events.map((e) => ({ ...e, created_by: SEED_IDS.ADMIN, created_at: now, updated_at: null })),
    spaces: spaces.map((s) => ({ ...s, created_at: now })),
    reservations: reservations.map((r) => ({ ...r, created_at: now })),
  };
}
